Added SSH Key comment field and fixed build for other users
maxgoedjen/secretive pull request #190
Opened 2020-12-25 09:13 UTC by lavalleeale

2020-12-27 23:35 UTC, maxgoedjen commented on Secretive/Controllers/AgentStatusChecker.swift
> +    let bundleID = Bundle.main.bundleIdentifier!.replacingOccurrences(of: "Host", with: "SecretAgent")
Overall big 👍  these changes.
This doesn't really need to be a property on the class though I don't think, you can just move this into the `secretAgentProcesses` block.

2020-12-27 23:35 UTC, maxgoedjen commented on Secretive/Controllers/LaunchAgentController.swift
> +    let bundleID = Bundle.main.bundleIdentifier!.replacingOccurrences(of: "Host", with: "SecretAgent")
Same here.

2020-12-27 23:44 UTC, maxgoedjen requested changes
Hey @vladimyr – thanks for the PR, sorry it took me so long to review.

Overall got some good changes – I think there might be a better storage strategy possible that we should experiment with though.

2020-12-27 23:44 UTC, maxgoedjen commented on Secretive/Views/CreateSecretView.swift
> +    let defaults = UserDefaults.standard
I'm not crazy about having this info stored in UserDefaults/View tbh, particularly for the SEP keys. 

My inclination would be to add a `kSecAttrComment` at the key creation https://github.com/maxgoedjen/secretive/blob/6c3748b6bfca9b6c5ba4c5214fb5e89130768b1b/SecretKit/SecureEnclave/SecureEnclaveStore.swift#L46

and read that out into a new property on `Secret`

2020-12-27 23:44 UTC, maxgoedjen commented on Secretive/Views/CreateSecretView.swift
> +    let defaults = UserDefaults.standard
(disclaimer: I haven't personally tested this yet so it might run into some issues, the SEP can be a bit weird that way sometimes)

We'll probably also need to figure out an approach for SmartCards.

2020-12-27 23:44 UTC, maxgoedjen commented on Secretive/Controllers/AgentStatusChecker.swift
> +    let bundleID = Bundle.main.bundleIdentifier!.replacingOccurrences(of: "Host", with: "SecretAgent")
`Bundle.main.bundleIdentifier!.replacingOccurrences(of: "Host", with: "SecretAgent")` this bit is repeated a couple times – might make sense to have a Bundle extension in SecretKit with like `hostBundleID` and `agentBundleID` properties.

2020-12-27 23:44 UTC, maxgoedjen commented on Secretive/Views/CreateSecretView.swift
> +            defaults.set(comment, forKey: name)
Having the comment be the default is nice 👍
(when we switch to the comment being on the keychain entry, I think it _probably_ makes sense to just to do this at view time, and not bake it in to the stored secret. This will make it nicer if the user changes their username, or has secrets created before this).

2020-12-27 23:47 UTC, vladimyr commented
@maxgoedjen I believe you tagged the wrong guy 😉

2020-12-27 23:51 UTC, maxgoedjen commented
@vladimyr betrayed by autocomplete! 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/342665/103181914-4f06c680-485b-11eb-8b8f-6b195168ddad.png">


![](https://media0.giphy.com/media/ohyNdetcfoJ9K/giphy.gif)

2020-12-28 01:19 UTC, lavalleeale commented
Hey, maybe I just read wrong, but I was under the impression that `kSecAttrComment` could not be changed after it was set. Obviously this PR doesn't  let you change the comment later, but that might be a good idea down the road.

2020-12-28 01:21 UTC, lavalleeale reviewed
Hey, I changed it to being an extension

2020-12-28 02:03 UTC, lavalleeale commented
Also, I don't know why, but if you see this soon and the check says failed, it looks like it just hasn't run yet? It built fine on my computer.

2020-12-28 02:45 UTC, maxgoedjen commented
> Hey, maybe I just read wrong, but I was under the impression that kSecAttrComment could not be changed after it was set. Obviously this PR doesn't let you change the comment later, but that might be a good idea down the road.

I'm not sure about that tbh, you could be right there. I'm not _terribly_ concerned with that if it is the case tho, since keys are basically immutable as is.

2020-12-28 02:45 UTC, maxgoedjen commented
@lavalleeale  looks like unit tests failed to build

```	Value of type 'Bundle' has no member 'hostBundleID'
1366
Test session results, code coverage, and logs:
1367
	Value of type 'Bundle' has no member 'agentBundleID'
1368
	/Users/runner/Library/Developer/Xcode/DerivedData/Secretive-acdauzrjufafyfgbbuwlkimwgdpy/Logs/Test/Test-Secretive-2020.12.28_02-41-23-+0000.xcresult
1369
	Value of type 'Bundle' has no member 'agentBundleID'
1370

1371
	Value of type 'Bundle' has no member 'agentBundleID'
1372
	Testing cancelled because the build failed.
1373
```

2020-12-28 02:46 UTC, maxgoedjen commented on SecretKit/Common/bundleIDs.swift
> +
```suggestion
```

2020-12-28 03:06 UTC, lavalleeale commented
Sorry about that, TIL that Xcode stores a reference of all the files in the project in the same file where it stores signing data

2020-12-28 06:50 UTC, maxgoedjen commented
All good, I miss it about half the time myself ;)

2020-12-28 07:02 UTC, lavalleeale commented
So is there anything else in the PR that you want me to fix?

2021-01-18 02:04 UTC, maxgoedjen commented
Hey @lavalleeale – sorry to be a bummer about this but I'm still pretty uncomfortable about storing metadata like this outside of the SEP. If we can find a way to remedy that I'd be receptive to a PR along those lines. (I'd also still gratefully merge the changes you made to the project to simplify signing/bundle IDs, if you'd be willing to split that out into a separate PR).

2021-01-18 03:32 UTC, maxgoedjen commented
I sketched out a few ideas we might be able to use to address this in #201 – it's probably a nontrivial amount of work so don't feel obligated to take it on yourself, I'll take a look at implementing for probably ~2.2.0 or so.

2021-01-18 05:46 UTC, lavalleeale commented
I'll take a look at the metadata idea, but comments are a part of the public key, which should be fine if it is public, right?

2021-01-18 06:08 UTC, maxgoedjen commented
> comments are a part of the public key, which should be fine if it is public, right?

To an extent. Like if you were looking at my keys on https://github.com/maxgoedjen.keys it's fine that you see the comments there. Having the comments be in a non-locked-down area like user defaults can potentially leak what services you're using (ie, another process could see that I use GitHub, that I have another Mac named XYZ, etc) which IMO somewhat violates the security expectations people have of the app.

2021-01-18 06:26 UTC, lavalleeale commented
I'm just saying that the last field in the public key is the comment, maybe specify it is part of the public key?

2021-01-19 03:20 UTC, closed without merging